spring.application.name=quizapp

spring.datasource.url=jdbc:postgresql://database-2.cbe6soqscva4.ap-south-1.rds.amazonaws.com:5432/postgreSQL
spring.datasource.username=postgre
spring.datasource.password=Administrator
spring.datasource.driver=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
